# Generated by Django 5.0.1 on 2024-02-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_articles_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
        migrations.AddField(
            model_name='articles',
            name='slug',
            field=models.SlugField(default='www', max_length=100),
        ),
        migrations.AlterField(
            model_name='articles',
            name='anons',
            field=models.CharField(max_length=6, verbose_name='Цена'),
        ),
    ]
